apiVersion: apps/v1
kind: Deployment
metadata:
  name: carassignment
  labels:
    app: carassignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carassignment
  template:
    metadata:
      labels:
        app: carassignment
    spec:
      containers:
        - name: carassignment
          image: "username/carassignment:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
