server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: carassignment
          uri: http://localhost:8082
          predicates:
            - Path=/dispatchRequests/**, /dispatchStatuses/**, /dispatchRequestSummaries/**, /dispatchRequestDetails/**, /dispatchStatusSummaries/**, /dispatchStatusDetails/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: carassignment
          uri: http://carassignment:8080
          predicates:
            - Path=/dispatchRequests/**, /dispatchStatuses/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
